### ISSUE TITLE
git-submodule-rewrite requires submodules checked out

### ISSUE THREAD

**Issue by qznc** [jeremysears/scripts#1]
If I just `git-clone` + `git-submodule-rewrite` without `git submodule update --init`, then the script fails with "fatal: No such section!".

**Comment by jeremysears** [comment]
So you have run `git clone <remote>` rather than `git clone --recursive <remote>` on the parent repo?  How would you like this to be handled?  Would you like to see additional validation w/ a more descriptive failure message, or are you thinking that the script should clone the submodules?

**Comment by qznc** [comment]
Well, ideally just do the right thing and make everything work magically. :smile: 

I'm not sure if just running `git submodule update --init --recursive` at the start is fine or might lose data?

At least, it should show a more helpful error message.

**Comment by jeremysears** [comment]
Not sure why this got closed.  That change isn't related.  Re-opening.

**Comment by jeremysears** [comment]
Fixed in the requested "make everything work magically" manner, in change [b053efe](https://github.com/jeremysears/scripts/commit/b053efebdeec311c35f5092c5c14dcb9a09d3027).
