### ISSUE TITLE
git-submodule-rewrite doesn't handle relative submodule url

### ISSUE THREAD

**Issue by noelwelsh** [jeremysears/scripts#11]
[The documentation](https://git-scm.com/docs/gitmodules) for the `.gitmodules` file states that a `url` property may be a path relative to the superproject's URI. E.g. if `foo` has a submodule `bar`, the `url` for `bar` maybe `../bar` if `bar's` origin is relative to `foo's`. The `git-submodule-rewrite` script doesn't handle this case. Specifically the url extracted on line 187 will be relative, and the clone on line 84 will fail.

**Comment by jeremysears** [comment]
It looks like your change won't work if if the remote is named anything other than "origin", but it otherwise looks fine to me.

**Comment by jeremysears** [comment]
Also, thank you for your contribution, Noel!
