### ISSUE TITLE
git-submodule-rewrite missing one space

### ISSUE THREAD

**Issue by KalleHallivuoriFuturice** [jeremysears/scripts#14]
> git-submodule-rewrite: line 214: [: missing `]'

Fix: `s/"]/" ]/`

**Comment by jeremysears** [comment]
Fixed.  Thanks, Kalle.  This gets enough use and changes that it should probably have some tests!  Sadly, since I no longer have any git-submodules, I don't have any driver to work on this, other than to keep it up for those who have also suffered w/ git submodules.

**Comment by KalleHallivuoriFuturice** [comment]
It worked great for us, no longer submodules here either, thanks to you! :)
