### ISSUE TITLE
git-submodule-rewrite, empty .gitmodules in submodule will break script

### ISSUE THREAD

**Issue by aronson** [jeremysears/scripts#18]
Hello, just used your script to fix up a massive project with many nested submodules.

I ran into an interesting bug, which hopefully will be easy to replicate. If you need more information let me know.

I had a tree of several super and sub repos that I progressively rewrote upwards using the script. I noticed that after bringing in two submodules in my middle-level repo (which was disconnected from the highest-level super repo at the time of running the script), the script would fail subtly on a subsequent run and not keep the history of the middle-level repo when rewriting it into the highest-level repo. Instead there would be a clone of the "submodule"'s old repo that was untracked in the super repo.

After some debugging, I found that my middle-level repo had a .gitmodules file that was empty. Deleting this empty file would restore normal functionality to the script. It appears that the script does not delete an empty .gitmodules file after the last submodule is removed. When this empty file exists in the repo (and this repo is itself a submodule of another repo), the script does not properly apply the final step(s) that attach the newly-rewritten submodule repository to the super repository.

I hope that my description was clear. I don't have time at the moment to visually display the issue, but if you need more details I will be happy to add them. I'm currently scrambling to use the results of my efforts at my workplace :)

I think the repro steps would be as such:

- Create a submodule with an empty .gitmodules file in its root
- Attempt to use the script to consolidate this submodule into a higher-level repo
- Observe that the final state of the higher-level repo is not as expected

**Comment by jeremysears** [comment]
Fixed in PR#26
