### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by cpoissonnier** [jeremysears/scripts#27]
You have no idea how much your script about un-submodule has been a blessing for me.

I just landed on a project that have been struggling with a lot of problems. Having too many repository (90+) is one of them, and thanks to your script, I managed to easily do something that would have been a struggle for me.

This is obviously not an issue, but it is important to thank the community for its helpful contribution.

Thank you Jeremy !

**Comment by jeremysears** [comment]
I'm glad to hear it, Clément.  Have a terrific weekend.
