### ISSUE TITLE
How to un-submodule multi-branch repo?

### ISSUE THREAD

**Issue by yanring** [jeremysears/scripts#28]
This script is great, but I'm having problems dealing with my multi-branch repo. 

Let's say I have master and dev, each of which has different commits, so I need to run the script for each of them. But this causes them both to have a huge commit: "Merge submodule contents for xxx"", which results in a very large .git file after the merge request, is there a way to slove this?

Thanks!

**Comment by robdesbois** [comment]
Once you've done both commits you could try garbage collecting with `git gc` - although the commit objects are different, if the merged submodule's files are the same they should still be consolidated. If you're ending up with a large `.git` directory though that suggests you may be merging rather different branches of the submodule.

Can you merge the 2 branches into a single branch then do the submodule merge? That's definitely the most straightforward approach. When I used this in a team, we finalised and merged changes on active branches so we only had to tackle this on `master`.

**Comment by yanring** [comment]
Thank you so much for your response!
Our team discussed it and concluded that keeping just one branch might be the best way to go, as you said.
