### ISSUE TITLE
This script looks great, but it is not working with my repository

### ISSUE THREAD

**Issue by hrushie** [jeremysears/scripts#32]
Hello Jeremy,

This script looks really promising but is there any guidelines for using it?

I am trying to use this script for merging our submodules into the main repo. it is taking 40 mins to to rewrite the history but when I am trying to push the changes it has only 2 changes in it.

1. remove .gitmodule file changes
2. remove submodule dir: libraries/app

I have cloned the main repo and executed the script in following manner

**git-submodule-rewrite libraries/app develop**

name of submodule is libraries/app. can you please point me out to the guidelines or what is wrong I am doing?

**Comment by jeremysears** [comment]
The only documentation is `git-submodule-rewrite --help`.  You might want to verify that you're using the right name.  It's located in .gitmodules.

**Comment by hrushie** [comment]
Actually I found out the issue the script is failing with following error while fetching the tags from submodule.

Error - Rejected (would clobber existing tag) 

I tried to do force fetch but it is overwriting the existing tag in main repository. any suggestions?

**Comment by hrushie** [comment]
Resolved this, closing this issue
