### ISSUE TITLE
printf: windows: invalid number

### ISSUE THREAD

**Issue by andrewtmendoza** [jeremysears/scripts#9]
The script works great, but in the output I noticed the following error:

```
/c/Users/path/to/git-submodule-rewrite.sh: line 59: printf: windows: invalid number
002008004000
```

**Comment by noelwelsh** [comment]
This is almost certainly the same as a problem I've observed on Mac OS. The underlying issue is that `git version` appends some non-numeric stuff after the version number. E.g., I see

```bash
$ git version
git version 2.13.5 (Apple Git-94)
```

The `(Apple Git-94)` part causes the error. Fix incoming.
